function [ output ] = dynamic( input )
%DYNAMIC Dynamic equations of the model (FULL DYNAMICS)
%   Function takes current control inputs, as well as velocities
%   vector generated by itself in the previous iteration, as inputs and
%   gives vector of velocities of the vehicle in the body frame as an
%   output.

%m1(u), m2(v), m3((w), m4(q), m5(r)
m1=2268+4380;
m2=2268+9518;
m3=2268+4268;
m4=2883+5000;
m5=2457+5000;


X_u=725;
Y_v=1240;
Z_w=825;
M_q=3000;
N_r=1804;

X_uu=1000;
Y_vv=525;
Z_ww=400;
M_qq=100;
N_rr=72;


N1=m1;
N2=m2;
N3=m3;
N4=m4;
N5=m5;

Tau_u=input(1);
Tau_r=input(2);
%Tau_w=input(3);
Tau_q=input(3);

u=input(4);
v=input(5);
r=input(6);
w=input(7);
q=input(8);

fu=input(9);
fv=input(10);
fr=input(11);
fw=input(12);
fq=input(13);

theta=input(14);

m=2268; gr=9.81;
z_g=0.1;
%x_g=0.1;

g4=z_g*m*gr*sin(theta); %+x_g*m*gr*cos(theta);

d11=X_u+X_uu*abs(u);  
d22=Y_v+Y_vv*abs(v);   
d33=Z_w+Z_ww*abs(w);  
d44=M_q+M_qq*abs(q);
d55=N_r+N_rr*abs(r);



Fxi1=-m3*w*q+m2*v*r-d11*u;          %F1u
Fxi2=-m1*u*r-d22*v;       %F2v
Fxi3=m1*u*q-d33*w;                  %F3w
F41=(m3-m1)*u*w-d44*q-g4; %gravitational forces
Fxi4=F41;                           %F4q
F51=(m1-m2)*u*v-d55*r;
Fxi5=F51;                           %F5r  


Tauxi4=Tau_q;
fxi4d=fq;
fxi5d=fr;

%xi1_dot=u_dot-T14*q_dot; xi2_dot=v_dot-T25*r_dot;
%xi3_dot=w_dot-T34*q_dot; xi4=q_dot; xi5=r_dot;
q_dot=(Fxi4+Tauxi4+fxi4d)/N4;
r_dot=(Fxi5+Tau_r+fxi5d)/N5; 
u_dot=(Fxi1+Tau_u+fu)/N1;  
v_dot=(Fxi2+fv)/N2; 
w_dot=(Fxi3+fw)/N3;                 


output=[u_dot; v_dot; r_dot; w_dot; q_dot];

end

