function [ output ] = kinematic( input )
%KINEMATIC Kinematic equations of the model
%   Function takes vector of velocities of the vehicle in the body frame 
%   [u; v; r], generated by the dynamic block and angle psi, generated by 
%   itself in the previous iteration, as inputs and gives current 
%   velocities in x, y axis, as well as angular velocity psi as an output.

u=input(1);
v=input(2);
r=input(3);
w=input(4);
q=input(5);
psi=input(6);
theta=input(7);


x_dot=u*cos(psi)*cos(theta)-v*sin(psi)+w*cos(psi)*sin(theta);
y_dot=u*sin(psi)*cos(theta)+v*cos(psi)+w*sin(psi)*sin(theta);
psi_dot=(1/cos(theta))*r;

z_dot=-u*sin(theta)+w*cos(theta);
theta_dot=q;



output=[x_dot; y_dot; psi_dot; z_dot; theta_dot];

end

